apiVersion: v2

name: hazelcast-platform-operator

description: A Helm chart for installing Hazelcast Platform Operator which automates common management tasks such as configuring, creating, scaling, and recovering Hazelcast clusters on Kubernetes and Red Hat OpenShift. By taking care of manual deployment and life-cycle management, Hazelcast Platform Operator makes it simpler to work with Hazelcast clusters.

type: application

version: "5.9.0"

appVersion: "5.9.0"

home: https://github.com/hazelcast/hazelcast-platform-operator

keywords:
  - Hazelcast
  - Operator

maintainers:
  - name: Hazelcast Cloud Native Team
    email: cloudnative@hazelcast.com

dependencies:
  - name: hazelcast-platform-operator-crds
    version: "5.9.0"
    condition: installCRDs