#!/bin/bash

set -e
set -o pipefail

echo "Authenticating gcloud..."
gcloud auth activate-service-account --key-file=${WORKSPACE}/jenkins-it-gke.json
gcloud auth list
gcloud auth configure-docker --quiet

echo "Configuring kubectl..."
gcloud container clusters get-credentials jenkins --zone us-central1-a --project hazelcast-33

MODIFIED_CHARTS=$(ct list-changed --config ${WORKSPACE}/test/ct.yaml | tr '\n' ' ')
IFS=' ' read -r -a charts <<< "$MODIFIED_CHARTS"
for chart in "${charts[@]}"
do
  if [ $chart == "stable/hazelcast" ]; then
    mkdir -p ${WORKSPACE}/stable/hazelcast/ci
    cat << 'EOF' > ${WORKSPACE}/stable/hazelcast/ci/jenkins_gke-values.yaml
nodeSelector:
  pool: standard
mancenter:
  licenseKey: MC_ENTERPRISE_LICENSE
  nodeSelector:
    pool: standard
  javaOpts: "-Dhazelcast.mc.rest.enabled=true"
EOF
    sed -i "s/MC_ENTERPRISE_LICENSE/\"${HAZELCAST_ENTERPRISE_LICENSE}\"/g" ${WORKSPACE}/stable/hazelcast/ci/jenkins_gke-values.yaml
  fi

  if [ $chart == "stable/hazelcast-enterprise" ]; then
    mkdir -p ${WORKSPACE}/stable/hazelcast-enterprise/ci
    cat << 'EOF' > ${WORKSPACE}/stable/hazelcast-enterprise/ci/jenkins_gke-values.yaml
hazelcast:
  licenseKey: HAZELCAST_ENTERPRISE_LICENSE
nodeSelector:
  pool: standard
mancenter:
  nodeSelector:
    pool: standard
  javaOpts: "-Dhazelcast.mc.rest.enabled=true"
EOF
    sed -i "s/HAZELCAST_ENTERPRISE_LICENSE/\"${HAZELCAST_ENTERPRISE_LICENSE}\"/g" ${WORKSPACE}/stable/hazelcast-enterprise/ci/jenkins_gke-values.yaml
  fi

  if [ $chart == "stable/hazelcast-jet-enterprise" ]; then
    sed -i "s/JET_ENTERPRISE_LICENSE/\"${JET_ENTERPRISE_LICENSE}\"/g" ${WORKSPACE}/stable/hazelcast-jet-enterprise/ci/jenkins_gke-values.yaml
  fi
done

ct lint --config ${WORKSPACE}/test/ct.yaml
ct install --config ${WORKSPACE}/test/ct.yaml
rm -rf ${WORKSPACE}/stable/hazelcast-enterprise/ci ${WORKSPACE}/stable/hazelcast/ci
