#!/bin/bash

set -e
set -o pipefail

echo "Authenticating gcloud..."
gcloud auth activate-service-account --key-file=${WORKSPACE}/jenkins-it-gke.json
gcloud auth list
gcloud auth configure-docker --quiet

echo "Configuring kubectl..."
gcloud container clusters get-credentials jenkins --zone us-central1-a --project hazelcast-33

MODIFIED_CHARTS=$(ct list-changed --config ${WORKSPACE}/test/ct.yaml | tr '\n' ' ')
if [[ "$MODIFIED_CHARTS" == *"hazelcast-enterprise"* ]]; then
    sed -i "s/HAZELCAST_ENTERPRISE_LICENSE/\"${HAZELCAST_ENTERPRISE_LICENSE}\"/g" ${WORKSPACE}/stable/hazelcast-enterprise/ci/jenkins_gke-values.yaml
fi

if [[ "$MODIFIED_CHARTS" == *"hazelcast-jet-enterprise"* ]]; then
    sed -i "s/JET_ENTERPRISE_LICENSE/\"${JET_ENTERPRISE_LICENSE}\"/g" ${WORKSPACE}/stable/hazelcast-jet-enterprise/ci/jenkins_gke-values.yaml
fi

ct lint --config ${WORKSPACE}/test/ct.yaml
ct install --config ${WORKSPACE}/test/ct.yaml
