#!/bin/bash

set -e
set -o pipefail

echo "Authenticating gcloud..."
gcloud auth activate-service-account --key-file=${WORKSPACE}/jenkins-it-gke.json
gcloud auth list
gcloud auth configure-docker --quiet

echo "Configuring kubectl..."
gcloud container clusters get-credentials jenkins --zone us-central1-a --project hazelcast-33

echo "Testing Hazelcast IMDG Chart and JET..."
ct lint-and-install --config ${WORKSPACE}/test/ct.yaml
