{{- if .Values.mancenter.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.mancenter.service.annotations }}
  annotations:
{{ toYaml .Values.mancenter.service.annotations | indent 4 }}
{{ else if and .Values.mcm.enabled .Values.mcm.baseURL }}
  annotations:
    name: Hazelcast Management Center
    id: applications
    roles: ClusterAdministrator,Administrator,Operator,Viewer
    url: "http://{{ template "mancenter.fullname" . }}-{{ .Release.Namespace }}.{{ .Values.mcm.baseURL }}"
{{- end }}
  name: {{ template "mancenter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- if and .Values.mcm.enabled .Values.mcm.baseURL }}
    inmenu: "true"
    target: ManagementCenter
{{- end }}
spec:
  type: {{ .Values.mancenter.service.type }}
  {{- if .Values.mancenter.service.clusterIP }}
  clusterIP: {{ .Values.mancenter.service.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.mancenter.service.type "LoadBalancer") (.Values.mancenter.service.loadBalancerIP)) }}
loadBalancerIP: {{ .Values.mancenter.service.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    role: mancenter
  ports:
  - protocol: TCP
    port: {{ .Values.mancenter.service.port }}
    targetPort: mancenter
    name: http
  - protocol: TCP
    port: {{ .Values.mancenter.service.httpsPort }}
    targetPort: mancenter
    name: https
{{- end }}
