{{- if and .Values.mancenter.enabled (and .Values.mancenter.yaml (not .Values.mancenter.existingConfigMap)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mancenter.fullname" . }}-configuration
  labels:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  hazelcast-client.yaml: |-
{{ toYaml .Values.mancenter.yaml | indent 4 }}
{{- end -}}
