{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hazelcast.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- range $key, $val := .Values.commonAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
