{{- if .Values.hazelcast.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "hazelcast.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  serviceName: {{ template "hazelcast.fullname" . }}
  replicas: {{ .Values.cluster.memberCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hazelcast.name" . }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      role: hazelcast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "hazelcast.name" . }}
        helm.sh/chart: {{ template "hazelcast.chart" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        role: hazelcast
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
      annotations:
        checksum/hazelcast-config: {{ toYaml .Values.hazelcast.yaml | sha256sum }}
        {{- range $key, $val := .Values.annotations }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.gracefulShutdown.enabled }}
      terminationGracePeriodSeconds: {{ .Values.gracefulShutdown.maxWaitSeconds }}
      {{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ if eq (int .Values.securityContext.runAsUser) 0 }}false{{ else }}true{{ end }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.topologySpreadConstraints | indent 8 }}
      {{- end }}
{{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
{{- end }}
      containers:
      - name: {{ template "hazelcast.fullname" . }}
        {{- if empty .Values.image.tag }}
        image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        {{- if .Values.customPorts }}
{{ toYaml .Values.customPorts | indent 8 }}
        {{- else }}
        - name: hazelcast
          containerPort: {{ if .Values.hostPort }}{{ .Values.hostPort }}{{ else }}5701{{ end }}
          {{- if .Values.hostPort }}
          hostPort: {{ .Values.hostPort }}
          {{- end }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: {{ .Values.metrics.service.portName }}
          containerPort: {{ .Values.metrics.service.port }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ if .Values.livenessProbe.port }}{{ .Values.livenessProbe.port }}{{ else if .Values.hostPort }}{{ .Values.hostPort }}{{ else }}5701{{ end }}
            scheme: {{ .Values.livenessProbe.scheme }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ if .Values.readinessProbe.port }}{{ .Values.readinessProbe.port }}{{ else if .Values.hostPort }}{{ .Values.hostPort }}{{ else }}5701{{ end }}
            scheme: {{ .Values.readinessProbe.scheme }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        {{- if .Values.hotRestart.enabled }}
        - name: hot-restart-persistence
          mountPath: /data/hot-restart
        {{- end }}
        {{- if .Values.secretsMountName }}
        - name: hazelcast-secrets
          mountPath: /data/secrets
        {{- end }}
        {{- if .Values.customVolume }}
        - name: hazelcast-custom
          mountPath: /data/custom
        {{- end }}
        {{- if .Values.externalVolume }}
        - name: hazelcast-external
          mountPath: /data/external
        {{- end }}
        env:
        {{- if .Values.hazelcast.licenseKeySecretName }}
        - name: HZ_LICENSEKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hazelcast.licenseKeySecretName }}
              key: key
        {{- else if .Values.hazelcast.licenseKey}}
        - name: HZ_LICENSEKEY
          value: {{ .Values.hazelcast.licenseKey }}
          {{- end }}
        {{- if .Values.customVolume }}
        - name: CLASSPATH
          value: "/data/custom:/data/custom/*"
        {{- end }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if .Values.metrics.enabled }}
        - name: PROMETHEUS_PORT
          value: "{{ .Values.metrics.service.port }}"
        {{- end }}
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName={{ template "hazelcast.serviceName" . }} -Dnamespace={{ .Release.Namespace }} -Dhazelcast.hotRestart={{ .Values.hotRestart.enabled }} -Dhz.jet.enabled={{ .Values.jet.enabled }} {{ if .Values.gracefulShutdown.enabled }}-Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait={{ .Values.gracefulShutdown.maxWaitSeconds }} {{ end }} -Dhazelcast.cluster.version.auto.upgrade.enabled={{ .Values.hazelcast.updateClusterVersionAfterRollingUpgrade }} {{ if .Values.metrics.enabled }}-Dhazelcast.jmx=true{{ end }} {{ .Values.hazelcast.javaOpts }}"
        {{- if .Values.hazelcast.loggingLevel }}
        - name: LOGGING_LEVEL
          value: {{ .Values.hazelcast.loggingLevel }}
        {{- end }}
        {{- with .Values.env }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsNonRoot: {{ if eq (int .Values.securityContext.runAsUser) 0 }}false{{ else }}true{{ end }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          privileged: false
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        {{- end }}
{{- if .Values.sidecarContainers }}
        {{- toYaml .Values.sidecarContainers | nindent 6 }}
{{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      serviceAccountName: {{ template "hazelcast.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      volumes:
        - name: hazelcast-storage
          configMap:
            {{- if .Values.hazelcast.existingConfigMap }}
            name: {{ .Values.hazelcast.existingConfigMap }}
            {{- else }}
            name: {{ template "hazelcast.fullname" . }}-configuration
            {{- end }}
        {{- if .Values.secretsMountName }}
        - name: hazelcast-secrets
          secret:
            secretName: {{ .Values.secretsMountName }}
        {{- end }}
        {{- if .Values.customVolume }}
        - name: hazelcast-custom
{{ toYaml .Values.customVolume | indent 10 }}
            {{- end }}
        {{- if .Values.hotRestart.enabled }}
        {{- if .Values.hotRestart.hostPath }}
        - name: hot-restart-persistence
          hostPath:
            path: {{ .Values.hotRestart.hostPath }}
        {{- end }}
        {{- if .Values.hotRestart.existingClaim }}
        - name: hot-restart-persistence
          persistentVolumeClaim:
            claimName: {{ .Values.hotRestart.existingClaim }}
        {{- end }}
        {{- end }}
        {{- if .Values.externalVolume }}
        - name: hazelcast-external
{{ toYaml .Values.externalVolume | indent 10 }}
        {{- end }}
  {{- if and (and (eq .Values.hotRestart.enabled true) (empty .Values.hotRestart.existingClaim)) (empty .Values.hotRestart.hostPath) }}
  volumeClaimTemplates:
  - metadata:
      name: hot-restart-persistence
      labels:
        app.kubernetes.io/name: {{ template "hazelcast.name" . }}
        helm.sh/chart: {{ template "hazelcast.chart" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    spec:
      accessModes:
      {{- range .Values.hotRestart.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.hotRestart.size | quote }}
      {{- if .Values.hotRestart.storageClass }}
      {{- if (eq "-" .Values.hotRestart.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.hotRestart.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
