{{- if .Values.mancenter.ingress.enabled -}}
{{- if and .Values.mancenter.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
{{- if not (hasKey .Values.mancenter.ingress.annotations "kubernetes.io/ingress.class") }}
{{- $_ := set .Values.mancenter.ingress.annotations "kubernetes.io/ingress.class" .Values.mancenter.ingress.className}}
{{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "mancenter.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- with .Values.mancenter.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if and .Values.mancenter.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.mancenter.ingress.className }}
{{- end }}
{{- if .Values.mancenter.ingress.tls }}
  tls:
  {{- range .Values.mancenter.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $serviceName := include "mancenter.fullname" . -}}
  {{- if .Values.mancenter.ingress.hosts }}
  {{- range $host := .Values.mancenter.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    name: http
  {{- end }}
  {{- else }}
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    name: http
  {{- end }}
{{- end }}
