{{- if and .Values.mancenter.enabled .Values.mancenter.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "mancenter.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "mancenter.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if or .Values.mancenter.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- merge nil .Values.mancenter.ingress.annotations .Values.commonAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.mancenter.ingress.className }}
{{- if .Values.mancenter.ingress.tls }}
  tls:
  {{- range .Values.mancenter.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $serviceName := include "mancenter.fullname" . -}}
  {{- if .Values.mancenter.ingress.hosts }}
  {{- range $host := .Values.mancenter.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    name: http
  {{- end }}
  {{- else }}
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    name: http
  {{- end }}
{{- end }}
