{{- if and (and .Values.mancenter.enabled .Values.mancenter.client.yaml) (not .Values.mancenter.existingClientConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mancenter.fullname" . }}-client-configuration
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
{{- range $key, $val := .Values.hazelcast.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
  hazelcast-client.yaml: |-
{{ toYaml .Values.mancenter.client.yaml | indent 4 }}
{{- end -}}
