{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.useClusterRole }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ template "hazelcast.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.rbac.useClusterRole }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ template "hazelcast.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "hazelcast.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
