{{- if .Values.webhook.enabled -}}
{{- $fullname := include "hazelcast-platform-operator.fullname" . -}}
{{- $ca := genCA "hazelcast-ca" 3650  -}}
{{- $cert := genSignedCert $fullname nil (list (printf "%s.%s.svc" $fullname .Release.Namespace ) (printf "%s.%s.svc.cluster.local" $fullname .Release.Namespace )) 3650 $ca  -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-cronhotbackup
    failurePolicy: Ignore
    name: vcronhotbackup.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cronhotbackups
    sideEffects: None
    namespaceSelector: 
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-hazelcast
    failurePolicy: Ignore
    name: vhazelcast.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - hazelcasts
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-hotbackup
    failurePolicy: Ignore
    name: vhotbackup.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - hotbackups
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-managementcenter
    failurePolicy: Ignore
    name: vmanagementcenter.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - managementcenters
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-map
    failurePolicy: Ignore
    name: vmap.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - maps
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-multimap
    failurePolicy: Ignore
    name: vmultimap.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - multimaps
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-queue
    failurePolicy: Ignore
    name: vqueue.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - queues
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-topic
    failurePolicy: Ignore
    name: vtopic.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - topics
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-wanreplication
    failurePolicy: Ignore
    name: vwanreplication.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - wanreplications
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-cache
    failurePolicy: Ignore
    name: vcache.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - caches
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-replicatedmap
    failurePolicy: Ignore
    name: vreplicatedmap.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - replicatedmaps
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-jetjob
    failurePolicy: Ignore
    name: vjetjob.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - jetjobs
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-wansync
    failurePolicy: Ignore
    name: vwansync.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - wansyncs
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $fullname }}
        namespace: {{ .Release.Namespace }}
        path: /validate-hazelcast-com-v1alpha1-hazelcastendpoint
    failurePolicy: Ignore
    name: vhazelcastendpoint.kb.io
    rules:
      - apiGroups:
          - hazelcast.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - hazelcastendpoints
    sideEffects: None
    namespaceSelector:
      {{- include "watched-namespaces.labelSelector" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc}}
  tls.key: {{ $cert.Key | b64enc }}
{{- end -}}