{{- if .Values.mcm.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ include "managementcenter.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "managementcenter.name" . }}
    helm.sh/chart: {{ template "hazelcast-jet.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  port:
    targetPort: mc-port
  to:
    kind: Service
    name: "{{ include "managementcenter.fullname" . }}"
{{- end }}