{{- if .Values.managementcenter.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.managementcenter.service.annotations }}
  annotations:
  {{ toYaml .Values.managementcenter.service.annotations | indent 4 }}
  {{ else if .Values.mcm.enabled }}
  annotations:
    name: Hazelcast Management Center
    id: applications
    roles: ClusterAdministrator,Administrator,Operator,Viewer
    url: "http://{{ template "managementcenter.fullname" . }}-{{ .Release.Namespace }}.{{ .Values.mcm.baseURL }}"
  {{- end }}
  name: {{ template "managementcenter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "managementcenter.name" . }}
    helm.sh/chart: {{ template "hazelcast-jet.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- if .Values.mcm.enabled }}
    inmenu: "true"
    target: ManagementCenter
{{- end }}
spec:
  type: {{ .Values.managementcenter.service.type }}
  {{- if .Values.managementcenter.service.clusterIP }}
  clusterIP: {{ .Values.managementcenter.service.clusterIP }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "managementcenter.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    role: managementcenter
  ports:
  - protocol: TCP
    port: {{ .Values.managementcenter.service.port }}
    targetPort: mc-port
    name: mc-port
  - protocol: TCP
    port: {{ .Values.managementcenter.service.httpsPort }}
    targetPort: mc-port
    name: mc-https-port
{{- end }}
