apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hazelcastOperator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
    helm.sh/chart: {{ template "hazelcastOperator.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.hazelcastOperator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
        helm.sh/chart: {{ template "hazelcastOperator.chart" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
      annotations:
        productID: hazelcast-operator
        productName: Hazelcast Operator
        productVersion: {{ .Values.hazelcastOperator.image.version }}
    spec:
      serviceAccountName: {{ template "hazelcastOperator.serviceAccountName" . }}

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: {{ template "hazelcastOperator.name" . }}
          image: {{ printf "%s:%s" .Values.hazelcastOperator.image.repository .Values.hazelcastOperator.image.version }}
          imagePullPolicy: {{ .Values.hazelcastOperator.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: hazelcast-operator
            - name: RELATED_IMAGE_HAZELCAST
              value: hazelcast/hazelcast:4.1.1
            - name: RELATED_IMAGE_MANCENTER
              value: hazelcast/management-center:4.2020.12
          resources:
            limits:
              cpu: "0.1"
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
