{{- if .Values.hazelcastOperator.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "hazelcastOperator.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
    helm.sh/chart: {{ template "hazelcastOperator.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - '*'
  - apiGroups:
    - ""
    - "extensions"
    resources:
    - ingresses
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    verbs:
    - get
    - create
    - list
    - update
    - delete
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - create
    - list
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - apps
    resourceNames:
    - hazelcast-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - hazelcast.com
    resources:
    - '*'
    verbs:
    - '*'
{{- end -}}
