{{- if .Values.hazelcastOperator.roleBinding.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "hazelcastOperator.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
    helm.sh/chart: {{ template "hazelcastOperator.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ template "hazelcastOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

roleRef:
  kind: ClusterRole
  name: {{ template "hazelcastOperator.fullname" . }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
