{{- if .Values.hazelcastOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hazelcastOperator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcastOperator.name" . }}
    helm.sh/chart: {{ template "hazelcastOperator.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- end -}}
