apiVersion: v1
appVersion: "0.7"
description: Hazelcast Jet Enterprise provides critical management features for scaling in-memory event stream processing across your IT landscape, including Management Center, Security Suite, Lossless Recovery, Rolling Job upgrades, and Enterprise PaaS Deployment Environments.
name: hazelcast-jet-enterprise
version: 1.0.0
keywords:
- hazelcast
- jet
- streaming
home: https://hazelcast.com/products/jet/enterprise/
icon: http://hazelcast.com/images/logos/Hazelcast-Jet-Logo-Blue_Light_Icon_200px.png
maintainers:
- name: emin
  email: emin@hazelcast.com
engine: gotpl
