name: Push Hazelcast-Platform-Operator Helm chart to the repo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "stable/hazelcast-platform-operator/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package operator chart and add it into index.yaml
        run: |
          helm package ./stable/hazelcast-platform-operator
          helm package ./stable/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds
          aws s3 cp s3://hazelcast-charts/index.yaml .
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com --merge ./index.yaml .

      - name: Push operator chart and index.yaml to S3 bucket
        run: |
          for CHART_TGZ in *.tgz; do aws s3 cp ${CHART_TGZ} s3://hazelcast-charts; done
          aws s3 cp ./index.yaml s3://hazelcast-charts

      - name: Create Kind Config
        run: |
          cat <<EOT >> ./kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          - role: worker
          - role: worker
          EOT

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          config: ./kind-config.yaml
          cluster_name: kind

      - name: Install and Verify Hazelcast Operator Image Tag
        run: |
          LATEST_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/hazelcast/hazelcast-platform-operator | jq -r '.version')
          helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com && \
          helm repo update && \
          helm install operator hazelcast/hazelcast-platform-operator --version=$LATEST_VERSION --set=installCRDs=true --set=phoneHomeEnabled=false --wait
          kubectl rollout status deployment.apps/operator-hazelcast-platform-operator
          kubectl wait pods -l app.kubernetes.io/name=hazelcast-platform-operator --for condition=Ready --timeout=180s
          INSTALLED_VERSION=$(kubectl get deployment operator-hazelcast-platform-operator -o=jsonpath="{.spec.template.spec.containers[*].image}" | awk -F ':' '{print $2}')
          if [[ ${LATEST_VERSION} == ${INSTALLED_VERSION} ]]; then
            echo "The latest operator image is successfully installed."
          else
            echo "The latest operator image tag doesn't equal the installed image tag."
            exit 1
          fi
